// Wallet actions
export const WALLET_SUCCESS = 'WALLET_SUCCESS';
export const WALLET_FAIL = 'WALLET_FAIL';
export const WALLET_HISTORY_SUCCESS = 'WALLET_HISTORY_SUCCESS';
export const WALLET_HISTORY_FAIL = 'WALLET_HISTORY_FAIL';
export const WALLET_WITHDRAW_SUCCESS = 'WALLET_WITHDRAW_SUCCESS';
export const WALLET_WITHDRAW_FAIL = 'WALLET_WITHDRAW_FAIL';

// Farmer actions
export const GET_AGENT_FARMER_SUCCESS = 'GET_AGENT_FARMER_SUCCESS';
export const GET_AGENT_FARMER_FAIL = 'GET_AGENT_FARMER_FAIL';
export const ADD_FARMER_SUCCESS = 'ADD_FARMER_SUCCESS';
export const ADD_FARMER_FAIL = 'ADD_FARMER_FAIL';

// Output actions
export const GET_OUTPUT_SUCCESS = 'GET_OUTPUT_SUCCESS';
export const GET_OUTPUT_FAIL = 'GET_OUTPUT_FAIL';
export const GET_ONE_OUTPUT_SUCCESS = 'GET_ONE_OUTPUT_SUCCESS';
export const GET_ONE_OUTPUT_FAIL = 'GET_ONE_OUTPUT_FAIL';
export const SELL_OUTPUT_SUCCESS = 'SELL_OUTPUT_SUCCESS';
export const SELL_OUTPUT_FAIL = 'SELL_OUTPUT_FAIL';
export const ADD_PRICE_SUCCESS = 'ADD_PRICE_SUCCESS';
export const ADD_PRICE_FAIL = 'ADD_PRICE_FAIL';
export const GET_MARKET_PRICE_SUCCESS = 'GET_MARKET_PRICE_SUCCESS';
export const GET_MARKET_PRICE_FAIL = 'GET_MARKET_PRICE_FAIL';

// Input actions
export const GET_ALL_INPUT_SUCCESS = 'GET_ALL_INPUT_SUCCESS';
export const GET_ALL_INPUT_FAIL = 'GET_ALL_INPUT_FAIL';
export const GET_ONE_INPUT_SUCCESS = 'GET_ONE_INPUT_SUCCESS';
export const GET_ONE_INTPUT_FAIL = 'GET_ONE_INTPUT_FAIL';
export const GET_INPUT_LOCATION_SUCCESS = 'GET_INPUT_LOCATION_SUCCESS';
export const GET_INPUT_LOCATION_FAIL = 'GET_INPUT_LOCATION_FAIL';
export const BUY_INPUT_SUCCESS = 'BUY_INPUT_SUCCESS';
export const BUY_INPUT_FAIL = 'BUY_INPUT_FAIL';

// variation actions
export const GET_STATES_AND_LGAS_SUCCESS = 'GET_STATES_AND_LGAS_SUCCESS';
export const GET_STATES_AND_LGAS_FAIL = 'GET_STATES_AND_LGAS_FAIL';
export const GET_STATES_SUCCESS = 'GET_STATES_SUCCESS';
export const GET_STATES_FAIL = 'GET_STATES_FAIL';
export const GET_LGAS_SUCCESS = 'GET_LGAS_SUCCESS';
export const GET_LGAS_FAIL = 'GET_LGAS_FAIL';
export const GET_BANKS_SUCCESS = 'GET_BANKS_SUCCESS';
export const GET_BANKS_FAIL = 'GET_BANKS_FAIL';
export const RESOLVE_BANK_ACCOUNTS_SUCCESS = 'RESOLVE_BANKS_ACCOUNTS_SUCCESS';
export const RESOLVE_BANK_ACCOUNTS_FAIL = 'RESOLVE_BANKS_ACCOUNTS_FAIL';

// commision actions
export const COMMISSION_WALLET_SUCCESS = 'COMMISSION_WALLET_SUCCESS';
export const COMMISSION_WALLET_FAIL = 'COMMISSION_WALLET_FAIL';
export const COMMISSION_HISTORY_SUCCESS = 'COMMISSION_HISTORY_SUCCESS';
export const COMMISSION_HISTORY_FAIL = 'COMMISSION_HISTORY_FAIL';
export const COMMISSION_FULL_HISTORY_SUCCESS =
  'COMMISSION_FULL_HISTORY_SUCCESS';
export const COMMISSION_FULL_HISTORY_FAIL = 'COMMISSION_FULL_HISTORY_FAIL';
export const COMMISSION_LEADERBOARD_SUCCESS = 'COMMISSION_LEADERBOARD_SUCCESS';
export const COMMISSION_LEADERBOARD_FAIL = 'COMMISSION_LEADERBOARD_FAIL';
export const COMMISSION_TRANSFER_SUCCESS = 'COMMISSION_TRANSFER_SUCCESS';
export const COMMISSION_TRANSFER_FAIL = 'COMMISSION_TRANSFER_FAIL';

export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const VERIFY_AUTH_SUCCESS = 'VERIFY_AUTH_SUCCESS';
export const VERIFY_AUTH_FAIL = 'VERIFY_AUTH_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_FAIL = 'OTP_FAIL';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAIL = 'VERIFY_OTP_FAIL';
export const USER_DETAILS = 'USER_DETAILS';
export const FORGOT_PIN_SUCCESS = 'FORGOT_PIN_SUCCESS';
export const FORGOT_PIN_FAIL = 'FORGOT_PIN_FAIL';
export const PIN_RESET_SUCCESS = 'PIN_RESET_SUCCESS';
export const PIN_RESET_FAIL = 'PIN_RESET_FAIL';
export const SET_RESET_PIN_OTP = 'SET_RESET_PIN_OTP';
export const SET_TOKEN = 'SET_TOKEN';
